gui:
  theme:
    activeBorderColor:
      - "#dac84e"
      - bold
    inactiveBorderColor:
      - "#d6c871"
    searchingActiveBorderColor:
      - "#9ad4a2"
      - bold
    optionsTextColor:
      - "#b7ccb7"
    selectedLineBgColor:
      - "#232c23"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#b7ccb7"
    cherryPickedCommitBgColor:
      - "#9ad4a2"
    markedBaseCommitFgColor:
      - "#9ad4a2"
    markedBaseCommitBgColor:
      - "#ffb4ab"
    unstagedChangesColor:
      - "#ffb4ab"
    defaultFgColor:
      - "#dbe6d8"
