gui:
  theme:
    activeBorderColor:
      - "#ffb2ba"
      - bold
    inactiveBorderColor:
      - "#ffb2ba"
    searchingActiveBorderColor:
      - "#feb877"
      - bold
    optionsTextColor:
      - "#e2c0a5"
    selectedLineBgColor:
      - "#35271c"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#e2c0a5"
    cherryPickedCommitBgColor:
      - "#feb877"
    markedBaseCommitFgColor:
      - "#feb877"
    markedBaseCommitBgColor:
      - "#ffb4ab"
    unstagedChangesColor:
      - "#ffb4ab"
    defaultFgColor:
      - "#f6decd"
