gui:
  theme:
    activeBorderColor:
      - "#e46769"
      - bold
    inactiveBorderColor:
      - "#d99759"
    searchingActiveBorderColor:
      - "#d9d659"
      - bold
    optionsTextColor:
      - "#b6afaf"
    selectedLineBgColor:
      - "#3e1e1e"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#b6afaf"
    cherryPickedCommitBgColor:
      - "#d9d659"
    markedBaseCommitFgColor:
      - "#d9d659"
    markedBaseCommitBgColor:
      - "#972325"
    unstagedChangesColor:
      - "#972325"
    defaultFgColor:
      - "#f3f2f2"
